id: swagger-api-custom

info:
  name: Public Swagger API - Detect
  author: pdteam,c-sh0
  severity: medium
  description: Public Swagger API was detected.
  reference: https://swagger.io/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  metadata:
    verified: true
    shodan-query: http.title:"swagger"
  tags: exposure,api,swagger

requests:
  - method: GET
    path:
      - "{{BaseURL}}/swagger-ui/swagger-ui.js?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/swagger/swagger-ui.js?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/swagger-ui.js?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/swagger/ui/swagger-ui.js?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/swagger/ui/index?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/swagger/index.html?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/swagger-ui.html?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/swagger/swagger-ui.html?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/swagger-ui.html?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api-docs/swagger.json?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api-docs/swagger.yaml?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api_docs?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/swagger.json?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/swagger.yaml?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/swagger/v1/swagger.json?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/swagger/v1/swagger.yaml?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/index.html?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/doc?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/docs/?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/swagger.json?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/swagger.yaml?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/swagger.yml?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/swagger/index.html?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/swagger/swagger-ui.html?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/api-docs/swagger.json?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/api-docs/swagger.yaml?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/swagger-ui/swagger.json?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/swagger-ui/swagger.yaml?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/apidocs/swagger.json?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/apidocs/swagger.yaml?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/swagger-ui/api-docs?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/doc.json?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/api-docs?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/apidocs?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/swagger?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/swagger/static/index.html?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/swagger-resources?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/swagger-resources/restservices/v2/api-docs?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/__swagger__/?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/_swagger_/?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/spec/swagger.json?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/spec/swagger.yaml?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/swagger/ui/index?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/__swagger__/?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/_swagger_/?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/v1/swagger-ui/swagger.json?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/v1/swagger-ui/swagger.yaml?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/swagger-resources/restservices/v2/api-docs?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api/swagger_doc.json?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/docu?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/docs?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/swagger?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/api-doc?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"
      - "{{BaseURL}}/beta/docs/?configUrl=https://raw.githubusercontent.com/itsbalvant/Swagger-UI-DOM-XSS/main/swagger.json"

    headers:
      Accept: text/html

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "document.domain"
          - "swagger:"
          - "Swagger 2.0"
          - "\"swagger\":"
          - "Swagger UI"
          - "loadSwaggerUI"
          - "**token**:"
          - "id=\"swagger-ui"
        condition: or

      - type: status
        status:
          - 200

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - " @version (v[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3})"

# Enhanced by mp on 2023/02/05
